package com.almworks.export.xml;

import com.almworks.export.FileExportParams;
import com.almworks.export.FileExporterUIHelper;
import com.almworks.util.AppBook;
import com.almworks.util.components.FileSelectionField;
import com.almworks.util.config.ConfigAttach;
import com.almworks.util.config.Configuration;
import com.almworks.util.model.ScalarModel;
import com.almworks.util.properties.PropertyMap;
import com.almworks.util.ui.actions.CantPerformException;
import org.almworks.util.detach.Detach;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;

public class XMLParametersForm extends FileExporterUIHelper {
    private JCheckBox myUseTempFile;
    private JLabel myTargetFileLabel;
    private FileSelectionField myTargetFile;
    private JPanel myWholePanel;

    public XMLParametersForm(Configuration config) {
        AppBook.replaceText("Export.XML.Form", myWholePanel);
        setupConfig(config);
        setupErrorModel(myTargetFile);
        setupFileChooser(myTargetFile, "XML files");
        setupUseTempFile(myUseTempFile, myTargetFile);
        setupVisual();
    }

    private void setupVisual() {
        myTargetFileLabel.setLabelFor(myTargetFile);
    }

    private void setupConfig(final Configuration config) {
        ConfigAttach.attachCheckbox(myLife, myUseTempFile, config, "useTempFile", true);
        ConfigAttach.attachTextField(myLife, myTargetFile.getField(), config, "targetFile", "");
    }

    protected String getDefaultExtension() {
        return "xml";
    }

    public Detach getDetach() {
        return myLife;
    }

    public JComponent getComponent() {
        return myWholePanel;
    }

    public void addParametersTo(PropertyMap parameters) {
        parameters.put(FileExportParams.TARGET_FILE, myTargetFile.getFile());
    }

    @NotNull
    public ScalarModel<String> getFormErrorModel() {
        return myErrorModel;
    }

    public void confirmExport() throws CantPerformException {
        checkFileOverwrite(myTargetFile, myWholePanel);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        myWholePanel = new JPanel();
        myWholePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        myUseTempFile = new JCheckBox();
        myUseTempFile.setText(":useTempFile");
        myWholePanel.add(myUseTempFile, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 2, 0));
        myWholePanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        myTargetFileLabel = new JLabel();
        myTargetFileLabel.setText(":file");
        panel1.add(myTargetFileLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        myTargetFile = new FileSelectionField();
        myTargetFile.setDefaultExtension("html");
        panel1.add(myTargetFile, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        myWholePanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myWholePanel;
    }
}
