package com.almworks.timetrack.gui;

import com.almworks.api.application.ModelKey;
import com.almworks.engine.gui.LargeTextFormlet;
import com.almworks.util.collections.Convertor;
import com.almworks.util.components.DesignPlaceHolder;
import com.almworks.util.ui.DocumentFormAugmentor;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import org.almworks.util.detach.Lifespan;

import javax.swing.*;
import java.awt.*;

public class ArtifactBoxViewer {
    private JPanel myWholePanel;
    private JLabel myIconsLabel;
    private DesignPlaceHolder myKeyPlace;
    private DesignPlaceHolder mySummaryPlace;

    public <V> ArtifactBoxViewer(
            Lifespan life, ModelKey<V> keyKey, Convertor<V, String> toStr, Convertor<String, V> fromStr,
            ModelKey<String> summaryKey) {
        LargeTextFormlet key = LargeTextFormlet.headerWithInt(keyKey, toStr, fromStr);
        key.adjustFont(-1, Font.BOLD, true);
        key.setLineWrap(false);
        key.getField().setMargin(new Insets(0, 0, 0, 0));
        myKeyPlace.setComponent(key.getComponent());

        LargeTextFormlet summary = LargeTextFormlet.withString(summaryKey, null);
        summary.adjustFont(0.9F, -1, true);
        summary.getField().setMargin(new Insets(0, 0, 0, 0));
        summary.getField().setColumns(0);
        summary.getField().setRows(0);
        mySummaryPlace.setComponent(summary.getComponent());

        myIconsLabel.setText(null);

        new DocumentFormAugmentor().augmentForm(life, myWholePanel, true);
        myWholePanel.setOpaque(false);
    }

    public JComponent getComponent() {
        return myWholePanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        myWholePanel = new JPanel();
        myWholePanel.setLayout(new FormLayout("fill:max(d;4dlu):noGrow,left:4dlu:noGrow,fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow"));
        myIconsLabel = new JLabel();
        myIconsLabel.setText("status icons ");
        CellConstraints cc = new CellConstraints();
        myWholePanel.add(myIconsLabel, cc.xy(1, 3));
        myKeyPlace = new DesignPlaceHolder();
        myKeyPlace.setName("key");
        myWholePanel.add(myKeyPlace, cc.xy(1, 1, CellConstraints.LEFT, CellConstraints.DEFAULT));
        mySummaryPlace = new DesignPlaceHolder();
        mySummaryPlace.setName("summary");
        myWholePanel.add(mySummaryPlace, cc.xywh(3, 1, 1, 5, CellConstraints.DEFAULT, CellConstraints.FILL));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        myWholePanel.add(spacer1, cc.xy(1, 5, CellConstraints.DEFAULT, CellConstraints.FILL));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myWholePanel;
    }
}
