package com.almworks.timetrack.gui;

import com.almworks.util.Pair;
import com.almworks.util.commons.Procedure;
import com.almworks.util.components.DesignPlaceHolder;
import com.almworks.util.ui.UIUtil;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;

/**
 * The form used to change the remaining time estimate in the Time Tracker.
 */
public class ChangeRemainingTimeForm extends BaseAdjustmentForm<Integer> {
    public static final int CANCEL = -1;
    public static final int REVERT = -3;

    private JPanel myWholePanel;
    private DesignPlaceHolder myEstimatePlace;
    private JButton myButton1;
    private JButton myButton2;

    private DurationField myEstimateField;

    public ChangeRemainingTimeForm(Integer currentEst) {
        initField(currentEst);
    }

    private void initField(Integer currentEst) {
        myEstimateField = new DurationField() {
            @Override
            public void addNotify() {
                super.addNotify();
                requestFocusInWindow();
                UIUtil.requestFocusLater(this);
            }
        };
        myEstimateField.setColumns(10);
        if (currentEst != null) {
            myEstimateField.setSeconds(currentEst);
        }
        myEstimatePlace.setComponent(myEstimateField);
    }

    protected void doCancel(Procedure<Integer> proc) {
        proc.invoke(CANCEL);
    }

    protected void doOk(Procedure<Integer> proc) {
        final int seconds = myEstimateField.getSeconds();
        if (seconds < 0) {
            if (myEstimateField.getText().trim().length() == 0) {
                proc.invoke(REVERT);
            } else {
                proc.invoke(CANCEL);
            }
        } else {
            proc.invoke(seconds);
        }
    }

    protected Pair<JButton, JButton> getButtons() {
        return Pair.create(myButton1, myButton2);
    }

    protected JComponent getFocusGrabber() {
        return myEstimateField;
    }

    protected JPanel getMainPanel() {
        return myWholePanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        myWholePanel = new JPanel();
        myWholePanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        final JLabel label1 = new JLabel();
        label1.setText("Remaining time:");
        CellConstraints cc = new CellConstraints();
        myWholePanel.add(label1, cc.xy(1, 1));
        myEstimatePlace = new DesignPlaceHolder();
        myEstimatePlace.setDesignRows(1);
        myWholePanel.add(myEstimatePlace, cc.xy(3, 1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):grow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:noGrow"));
        ((FormLayout) panel1.getLayout()).setColumnGroups(new int[][]{new int[]{3, 5}});
        myWholePanel.add(panel1, cc.xyw(1, 3, 3));
        myButton2 = new JButton();
        myButton2.setText("btn2");
        panel1.add(myButton2, cc.xy(5, 1));
        myButton1 = new JButton();
        myButton1.setText("btn1");
        panel1.add(myButton1, cc.xy(3, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myWholePanel;
    }
}
