package com.almworks.engine.items;

import com.almworks.api.gui.DialogBuilder;
import com.almworks.api.gui.DialogManager;
import com.almworks.util.Terms;
import com.almworks.util.components.AScrollPane;
import com.almworks.util.components.SizeDelegate;
import com.almworks.util.i18n.Local;
import com.almworks.util.ui.actions.ActionContext;
import com.almworks.util.ui.actions.CantPerformException;
import com.almworks.util.ui.actions.SimpleAction;
import com.almworks.util.ui.actions.UpdateContext;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

class CleanDBForm {
    private JPanel myWholePanel;
    private JTextArea myMessage;
    private JCheckBox myBackup;
    private AScrollPane myMessagePane;
    private JLabel myIconPlace;
    private boolean myErase = false;

    CleanDBForm() {
        Icon warningIcon = UIManager.getIcon("OptionPane.informationIcon");
        if (warningIcon == null) myIconPlace.setVisible(false);
        else myIconPlace.setIcon(warningIcon);
        myMessagePane.setSizeDelegate(new SizeDelegate.Fixed().setMinHeight(10).setMinWidth(10).setPrefWidth(230));
        myMessage.setBorder(null);
        myMessage.setOpaque(false);
        myMessagePane.getViewport().setOpaque(false);
        myMessagePane.setOpaque(false);
        myMessagePane.setBorder(null);
    }

    public static CleanDBForm showDialog(DialogManager manager, String problem) {
        final CleanDBForm form = new CleanDBForm();
        form.myMessage.setText(problem);
        final DialogBuilder builder = manager.createBuilder("cleanDBConfirmation");
        builder.setTitle(Local.text(Terms.key_Deskzilla));
        builder.setContent(form.myWholePanel);
        builder.addAction(new SimpleAction("&Continue") {
            @Override
            protected void customUpdate(UpdateContext context) throws CantPerformException {
            }

            @Override
            protected void doPerform(ActionContext context) throws CantPerformException {
                form.myErase = true;
                builder.closeWindow();
            }
        });
        builder.setCancelAction(SimpleAction.createDoNothing("E&xit Application"));
        builder.setModal(true);
        builder.setIgnoreStoredSize(true);
        builder.showWindow();
        return form;
    }

    public boolean isErase() {
        return myErase;
    }

    public boolean isBackup() {
        return myBackup.isSelected();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        myWholePanel = new JPanel();
        myWholePanel.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow", "fill:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        myBackup = new JCheckBox();
        myBackup.setSelected(true);
        myBackup.setText("Create Backup Copy");
        myBackup.setMnemonic('B');
        myBackup.setDisplayedMnemonicIndex(7);
        CellConstraints cc = new CellConstraints();
        myWholePanel.add(myBackup, cc.xyw(1, 5, 3));
        myMessagePane = new AScrollPane();
        myWholePanel.add(myMessagePane, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.FILL));
        myMessage = new JTextArea();
        myMessage.setEditable(false);
        myMessage.setLineWrap(true);
        myMessage.setWrapStyleWord(true);
        myMessagePane.setViewportView(myMessage);
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, -1, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("To clear the database, click Continue.");
        myWholePanel.add(label1, cc.xy(3, 3));
        myIconPlace = new JLabel();
        myIconPlace.setText("");
        myWholePanel.add(myIconPlace, cc.xywh(1, 1, 1, 3));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myWholePanel;
    }
}
