package com.almworks.spi.provider.wizard;

import com.almworks.util.components.URLLink;
import com.almworks.util.components.plaf.macosx.Aqua;
import com.almworks.util.i18n.Local;
import com.almworks.util.ui.ScrollBarPolicy;
import com.almworks.util.ui.UIUtil;
import com.almworks.util.ui.swing.SwingTreeUtil;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import java.awt.*;

/**
 * GUI form for the New Connection wizard's connection name page.
 */
public class ConnectionNameForm {
    JPanel myWholePanel;
    JTextField myNameField;
    URLLink myUrlLink;
    JLabel myUserTermLabel;
    JLabel myUserLabel;
    JLabel myUnitsLabel;
    JTextArea myUnitsArea;

    public ConnectionNameForm() {
        adjustToPlatform();
        adjustToTracker();
        configureUnitsArea();
        final Border textFieldBorder = createTextFieldBorder();
        configureLinkAndLabel(textFieldBorder);
        configureEnclosingScrollPane(textFieldBorder);
    }

    private void adjustToPlatform() {
        myUrlLink.putClientProperty(UIUtil.SET_DEFAULT_LABEL_ALIGNMENT, false);
        myUserLabel.putClientProperty(UIUtil.SET_DEFAULT_LABEL_ALIGNMENT, false);
        UIUtil.setDefaultLabelAlignment(myWholePanel);
        Aqua.disableMnemonics(myWholePanel);
    }

    private void adjustToTracker() {
        myUserTermLabel.setText(Local.text("app.term.Username") + ":");
    }

    private void configureUnitsArea() {
        myUnitsArea.setOpaque(false);
        myUnitsArea.setRows(10);
        myUnitsArea.setDragEnabled(false);
        myUnitsArea.setBorder(null);
    }

    private Border createTextFieldBorder() {
        final Insets insets = myNameField.getBorder().getBorderInsets(myNameField);
        return new EmptyBorder(0, insets.left, 0, insets.right);
    }

    private void configureLinkAndLabel(Border textFieldBorder) {
        myUrlLink.setBorder(textFieldBorder);
        myUserLabel.setBorder(textFieldBorder);
    }

    private void configureEnclosingScrollPane(Border textFieldBorder) {
        final JScrollPane jsp = SwingTreeUtil.findAncestorOfType(myUnitsArea, JScrollPane.class);
        if (jsp != null) {
            jsp.setBorder(textFieldBorder);
            jsp.getViewport().setOpaque(false);
            jsp.setOpaque(false);
            ScrollBarPolicy.AS_NEEDED.setBoth(jsp);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        myWholePanel = new JPanel();
        myWholePanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:noGrow,top:3dlu:noGrow,center:d:noGrow,top:3dlu:noGrow,center:d:noGrow,top:3dlu:noGrow,center:max(d;16dlu):grow"));
        ((FormLayout) myWholePanel.getLayout()).setRowGroups(new int[][]{new int[]{3, 5}});
        final JLabel label1 = new JLabel();
        label1.setText("Name:");
        label1.setDisplayedMnemonic('M');
        label1.setDisplayedMnemonicIndex(2);
        CellConstraints cc = new CellConstraints();
        myWholePanel.add(label1, cc.xy(1, 1));
        myNameField = new JTextField();
        myWholePanel.add(myNameField, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("URL:");
        myWholePanel.add(label2, cc.xy(1, 3));
        myUrlLink = new URLLink();
        myUrlLink.setHorizontalAlignment(2);
        myUrlLink.setUrl("http://");
        myWholePanel.add(myUrlLink, cc.xy(3, 3, CellConstraints.LEFT, CellConstraints.DEFAULT));
        myUserTermLabel = new JLabel();
        myUserTermLabel.setText("Username:");
        myWholePanel.add(myUserTermLabel, cc.xy(1, 5));
        myUserLabel = new JLabel();
        myUserLabel.setText("Label");
        myWholePanel.add(myUserLabel, cc.xy(3, 5));
        myUnitsLabel = new JLabel();
        myUnitsLabel.setText("Projects:");
        myWholePanel.add(myUnitsLabel, cc.xy(1, 7, CellConstraints.DEFAULT, CellConstraints.TOP));
        final JScrollPane scrollPane1 = new JScrollPane();
        myWholePanel.add(scrollPane1, cc.xy(3, 7, CellConstraints.FILL, CellConstraints.FILL));
        myUnitsArea = new JTextArea();
        myUnitsArea.setEditable(false);
        myUnitsArea.setFocusable(false);
        scrollPane1.setViewportView(myUnitsArea);
        label1.setLabelFor(myNameField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myWholePanel;
    }
}
