package com.almworks.explorer.qbuilder.filter;

import com.almworks.util.AppBook;
import com.almworks.util.components.AComboBox;
import com.almworks.util.components.ADateField;
import com.almworks.util.properties.PropertyMap;
import com.almworks.util.ui.ModelMapDialogEditor;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;

/**
 * @author dyoma
 */
public class SpecificDate extends ModelMapDialogEditor {
    public static final DateBoundParams PARAMS = new DateBoundParams("SpecificDate", false);
    private JRadioButton myRelative;
    private JRadioButton myAbsolute;
    private JTextField myFromNow;
    private AComboBox<DateUnit> myUnits;
    private ADateField myDate;
    private JPanel myWholePanel;

    public SpecificDate(@NotNull PropertyMap values) {
        super(values);
        $$$setupUI$$$();
        AppBook.replaceText(DateConstraintEditor.BOOK_PREFIX, myWholePanel);
        PARAMS.install(getBinder(), new DateBoundParams.Components(null, myRelative, myAbsolute, myFromNow, myUnits, myDate));
//    new DateBoundController(myRelative, myAbsolute, myFromNow, myUnits, myDate, false);
    }

    public JComponent getComponent() {
        return myWholePanel;
    }

    private void createUIComponents() {
        myDate = new ADateField(ADateField.Precision.DAY);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        myWholePanel = new JPanel();
        myWholePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), 4, 2));
        myUnits = new AComboBox();
        myUnits.setColumns(11);
        myWholePanel.add(myUnits, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        myRelative = new JRadioButton();
        myRelative.setText(":relative");
        myWholePanel.add(myRelative, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        myAbsolute = new JRadioButton();
        myAbsolute.setText(":absolute");
        myWholePanel.add(myAbsolute, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        myFromNow = new JTextField();
        myFromNow.setColumns(5);
        myWholePanel.add(myFromNow, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        myDate.setColumns(10);
        myWholePanel.add(myDate, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myWholePanel;
    }
}
