package com.almworks.export.pdf;

import com.almworks.export.FileExporterUIHelper;
import com.almworks.util.AppBook;
import com.almworks.util.components.FileSelectionField;
import com.almworks.util.config.ConfigAttach;
import com.almworks.util.config.Configuration;
import com.almworks.util.properties.PropertyMap;
import com.almworks.util.ui.actions.CantPerformException;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;

public class PDFParametersForm extends FileExporterUIHelper {
    private JPanel myWholePanel;
    private JCheckBox myCommentsCheckBox;
    private JCheckBox myGraphicsAttachesCheckBox;
    private JCheckBox myTextAttachesCheckBox;
    private FileSelectionField myTargetFile;
    private JCheckBox myOnNewPage;
    private JCheckBox myCompactAttributes;
    private JCheckBox myUseTempFile;

    private final Configuration myConfig;

    public PDFParametersForm(Configuration config) {
        myConfig = config;
        AppBook.replaceText("Export.PDF.Form", myWholePanel);
        setupConfig(config);
        setupFileChooser(myTargetFile, "PDF files");
        setupErrorModel(myTargetFile);
        setupUseTempFile(myUseTempFile, myTargetFile);
    }

    private void setupConfig(Configuration config) {
        ConfigAttach.attachCheckbox(myLife, myCommentsCheckBox, config, "printComments", true);
        ConfigAttach.attachCheckbox(myLife, myGraphicsAttachesCheckBox, config, "printGraphAttach", true);
        ConfigAttach.attachCheckbox(myLife, myTextAttachesCheckBox, config, "printTextAttach", true);
        ConfigAttach.attachCheckbox(myLife, myCompactAttributes, config, "printCompact", true);
        ConfigAttach.attachCheckbox(myLife, myOnNewPage, config, "printOnNewPage", true);
        ConfigAttach.attachTextField(myLife, myTargetFile.getField(), config, "targetFile", "");
        ConfigAttach.attachCheckbox(myLife, myUseTempFile, config, "useTempFile", true);
    }

    protected String getDefaultExtension() {
        return "pdf";
    }

    public void confirmExport() throws CantPerformException {
        checkFileOverwrite(myTargetFile, myWholePanel);
    }

    public JComponent getComponent() {
        return myWholePanel;
    }

    public void addParametersTo(PropertyMap parameters) {
        parameters.put(PDFParams.TARGET_FILE, myTargetFile.getFile());
        parameters.put(PDFParams.COMMENTS, myCommentsCheckBox.isSelected());
        parameters.put(PDFParams.ATTACH_GRAPH, myGraphicsAttachesCheckBox.isSelected());
        parameters.put(PDFParams.ATTACH_TEXT, myTextAttachesCheckBox.isSelected());
        parameters.put(PDFParams.ON_NEW_PAGE, myOnNewPage.isSelected());
        parameters.put(PDFParams.COMPACT_TABLE, myCompactAttributes.isSelected());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        myWholePanel = new JPanel();
        myWholePanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        ((FormLayout) myWholePanel.getLayout()).setRowGroups(new int[][]{new int[]{1, 5, 7}});
        final JLabel label1 = new JLabel();
        label1.setText(":file");
        CellConstraints cc = new CellConstraints();
        myWholePanel.add(label1, cc.xy(1, 1));
        myCompactAttributes = new JCheckBox();
        myCompactAttributes.setText(":compact");
        myWholePanel.add(myCompactAttributes, cc.xyw(1, 7, 3));
        myTargetFile = new FileSelectionField();
        myWholePanel.add(myTargetFile, cc.xyw(3, 1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        myOnNewPage = new JCheckBox();
        myOnNewPage.setSelected(false);
        myOnNewPage.setText(":onNewPage");
        myWholePanel.add(myOnNewPage, cc.xyw(1, 5, 3));
        myUseTempFile = new JCheckBox();
        myUseTempFile.setText(":useTempFile");
        myWholePanel.add(myUseTempFile, cc.xyw(1, 3, 3));
        myTextAttachesCheckBox = new JCheckBox();
        myTextAttachesCheckBox.setText(":textAttach");
        myWholePanel.add(myTextAttachesCheckBox, cc.xy(5, 3));
        myGraphicsAttachesCheckBox = new JCheckBox();
        myGraphicsAttachesCheckBox.setText(":graphAttach");
        myWholePanel.add(myGraphicsAttachesCheckBox, cc.xy(5, 5));
        myCommentsCheckBox = new JCheckBox();
        myCommentsCheckBox.setText(":comments");
        myWholePanel.add(myCommentsCheckBox, cc.xy(5, 7));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myWholePanel;
    }
}
